version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{checksum "package.json"}}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Build typescript
          command: npm run build:tsc
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build